#!/bin/bash

ESPRESSO_PATH=$1
ESPRESSO_FILE=${ESPRESSO_PATH##*/}
ESPRESSO_NAME=${ESPRESSO_FILE%.*}
ESPRESSO_OUT="build/$ESPRESSO_NAME"

mkdir -p build

g++ \
  -std=c++11 \
  --include-directory=. \
  --include-directory=lib/virtuino \
  --include-directory=lib \
  -o $ESPRESSO_OUT \
  $ESPRESSO_PATH \
  && eval "./$ESPRESSO_OUT ${@:2}"
