#!/bin/sh

YPSTEST_PATH=$1
YPSTEST_FILE=${YPSTEST_PATH##*/}
YPSTEST_NAME=${YPSTEST_FILE%.*}
YPSTEST_OUT="build/$YPSTEST_NAME"

clang++ \
  -std=c++11 \
  --include-directory=. \
  --include-directory=lib \
  -o $YPSTEST_OUT \
  $YPSTEST_PATH \
  && eval ./$YPSTEST_OUT
