name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build environment
      run: docker build -t espresso .
    - name: Unit Tests
      run: docker run --rm espresso test/unit-tests/all.cpp
    - name: Integration Test - Blinker
      run: docker run --rm espresso test/integration-tests/blinker/blinker.spec.cpp
    - name: Integration Test - Button LED
      run: docker run --rm espresso test/integration-tests/button-led/button-led.spec.cpp
    - name: Integration Test - Debouncing
      run: docker run --rm espresso test/integration-tests/debouncing/debouncing.spec.cpp
    - name: Integration Test - Game Buzzer
      run: docker run --rm espresso test/integration-tests/game-buzzer/game-buzzer.spec.cpp
    - name: Integration Test - Multiplexing
      run: docker run --rm espresso test/integration-tests/multiplexing/multiplexing.spec.cpp
    - name: Integration Test - Traffic Lights
      run: docker run --rm espresso test/integration-tests/traffic-lights/traffic-lights.spec.cpp
